### ISSUE TITLE
删除组件失效，保存和预览大屏失效。。。

### ISSUE THREAD

**Issue by huangfuying98** [ggymm/data-view-web#3]

**Comment by ggymm** [comment]
删除功能已经添加了，但是只是初步实现，可能会有隐藏BUG
保存和预览失效不知道你是不是看的这个[Demo Create](http://49.233.166.224/data-view-web/data-view-instance/create)
这个只有设计器的基础功能，保存和预览是需要后台支持的。所以需要下载前后台代码自行运行才能看到效果

**Comment by huangfuying98** [comment]
才学疏浅了，没有学过go语言。。请问运行main.go就可以搭建后台了吗？

**Comment by ggymm** [comment]
> 才学疏浅了，没有学过go语言。。请问运行main.go就可以搭建后台了吗？

这个看你需求了，后端就几个接口。很简单的。用java重新实现也用不了多少时间
想启动项目的话
1. 首先有go的环境，下载sdk，配置环境变量
2. 然后安装依赖，在项目根目录执行go mod tidy和go mod vendor
3. 执行在_build目录下的python打包脚本
4. 双击执行exe就可以了

**Comment by huangfuying98** [comment]
关键是后端没有说明文档，无从下手啊。

**Comment by huangfuying98** [comment]
python打包的时候报错：
拷贝其他文件目录
Traceback (most recent call last):
  File "C:\Users\hhhfy\IntelliJIDEAProjects\data-view\_build\build.py", line 82, in <module>
    shutil.rmtree(os.path.join(code_dir, build_folder, "linux", "storage"))
  File "C:\ProgramData\Anaconda3\envs\data-view\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\Anaconda3\envs\data-view\lib\shutil.py", line 599, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\ProgramData\Anaconda3\envs\data-view\lib\shutil.py", line 596, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\hhhfy\\IntelliJIDEAProjects\\data-view\\_build\\linux\\storage'

**Comment by huangfuying98** [comment]
不过好像exe文件是运行起来了，但是前端保存文件的时候，提示
“保存失败, Error 1045: Access denied for user 'root'@'localhost' (using password: YES)”

**Comment by ggymm** [comment]
> 不过好像exe文件是运行起来了，但是前端保存文件的时候，提示
> “保存失败, Error 1045: Access denied for user 'root'@'localhost' (using password: YES)”

配置文件（config.toml）里面把数据库连接账号密码改一下

**Comment by ggymm** [comment]
> 关键是后端没有说明文档，无从下手啊。

这样吧，我加些文档，说明下项目接口和接口作用

**Comment by ggymm** [comment]
你可以去后端仓库看下了，我在issue中写了一些说明。有不懂的可以再问我

**Comment by huangfuying98** [comment]
> 你可以去后端仓库看下了，我在issue中写了一些说明。有不懂的可以再问我

好的，看到了，感谢。现在后端存在的问题是数据库没有初始化，改了config.toml后启动还是没有在数据库里找到data-view，是不是go语言要连接数据库还要设置些别的东西？

**Comment by ggymm** [comment]
> > 你可以去后端仓库看下了，我在issue中写了一些说明。有不懂的可以再问我
> 
> 好的，看到了，感谢。现在后端存在的问题是数据库没有初始化，改了config.toml后启动还是没有在数据库里找到data-view，是不是go语言要连接数据库还要设置些别的东西？

后端 _doc目录下有数据库结构

**Comment by ggymm** [comment]
没有问题我就关了，有问题去服务端项目那里提吧
