### ISSUE TITLE
预览大屏不显示坐标轴；设置图片背景无法导入图片；默认的模板如何导入？

### ISSUE THREAD

**Issue by huangfuying98** [ggymm/data-view-web#4]

**Comment by ggymm** [comment]
1. 预览不显示坐标轴，是否可以提供图片或者视频
2. 图片上传可以暂时使用后端服务的这个地址进行上传: http://localhost:9421/api/v1/image/upload.html
3. 默认模板是指什么？我做的示例模板由于版权问题，我删除了模板数据SQL文件。暂时无法提供，如果需要研究学习可以加下QQ讨论群（177745111）。我在群里放了一份比较简单的模板

**Comment by ggymm** [comment]
没有新的问题我就关闭了，需要的时候再打开吧
